######################################################################
# Arquivo de configuracao
######################################################################

# extensao dos pacotes: chilios=chi.zst, mazon=mz
#PKG_EXT='mz'			#mazonos
PKG_EXT='chi.zst'		#ChiliOS

# site de hospedagem da distro
PKG_SITE='http://localhost'
#PKG_SITE='http://201.7.66.107'
#PKG_SITE='http://mazonos.com'
#PKG_SITE='https://github.com/vcatafesta/ChiliOS/tree/master'
PKG_RAW_FILE='https://raw.githubusercontent.com/vcatafesta/ChiliOS/master/packages/t/tree-1.8.0-2.chi.zst'
PKG_RAW='https://raw.githubusercontent.com/vcatafesta/ChiliOS/master'
AUTO_YES='1'
MAINTAINER='Vilmar Catafesta <vcatafesta@gmail.com>'
GPG_SIGN='0'
CREATE_SHA256='0'
DESC_BUILD='2'
REWRITE_SIG='1'
URL='http://www.linuxfromscratch.org/lfs/view/systemd/'
LICENSE='GPL2'
LFS_VERSION='8.4'
LFS_INIT='SYSTEMD'
ARCH='x86_64'
DISTRO='chili'
LFS_VARCACHE='fetch'
GITDIR='/github/ChiliOS'
PKGCORE="$GITDIR/packages/core"
PKGDIR="$PKGCORE"
ALIEN_CACHE_DIR='/var/cache/pacman/pkg'
IGNOREPKG=('glibc' 'file')

# pacotes hospedado no repositorio do github: sim='1', nao='0'
GITSITE='0'
