[AutomaticTranslation]
Enabled=False

[FMain]
Geometry=[0,0,958,1015,0]
panProject=[False,203,True]
panProperty=[False,224,True]
panDebug=[True,98,True]

[FOutput]
Geometry=[0,0,679,378,0]

[FProperty]
Geometry=[0,0,224,482,0]
spnHelp=[False,91,True]

[FSidePanel]
panTool=[False,259,True]

[FWelcome]
SortRecent=0

[General]
ShowTipOnStartup=-1
LastTip=1

